version: '3.8'
services:
  db:
    container_name: pg
    image: postgres
    restart: always
    environment: # depends on .env
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    logging:
      options:
        max-size: '12m'
        max-file: '5'
      driver: json-file
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment: # depends on .env
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      PGADMIN_DEFAULT_EMAIL: '${PGADMIN_DEFAULT_EMAIL}'
      PGADMIN_DEFAULT_PASSWORD: '${PGADMIN_DEFAULT_PASSWORD}'
    ports:
      - '5050:80'
    depends_on:
      - db
    logging:
      options:
        max-size: '12m'
        max-file: '5'
      driver: json-file
  translate:
    container_name: translate
    build:
      context: ./
      dockerfile: ./dockerfiles/Dockerfile.translate
    restart: always
    network_mode: host
    volumes:
      - ./packages/translate2:/usr/app
    command: python ./main.py
    environment: # depends on .env
      CI: '${CI}'
    logging:
      options:
        max-size: '12m'
        max-file: '5'
      driver: json-file
