version: '3.8'
services:
  db:
    container_name: db
    image: postgres
    restart: always
    environment: # depends on .env
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    logging:
      options:
        max-size: '12m'
        max-file: '5'
      driver: json-file
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment: # depends on .env
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      PGADMIN_DEFAULT_EMAIL: '${PGADMIN_DEFAULT_EMAIL}'
      PGADMIN_DEFAULT_PASSWORD: '${PGADMIN_DEFAULT_PASSWORD}'
    ports:
      - '5050:80'
    depends_on:
      - db
    logging:
      options:
        max-size: '12m'
        max-file: '5'
      driver: json-file
  translate:
    container_name: translate
    build:
      context: ./
      dockerfile: ./dockerfiles/Dockerfile.translate
    restart: always
    ports:
      - '8000:8000'
    volumes:
      - ./packages/translate2:/usr/app
    command: python ./main.py
    environment: # depends on .env
      CI: '${CI}'
    logging:
      options:
        max-size: '12m'
        max-file: '5'
      driver: json-file
  web:
    image: nginx
    volumes:
      - ./resources/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./resources/ws.nginx.conf:/etc/nginx/conf.d/ws.nginx.conf
      - ./resources/api.nginx.conf:/etc/nginx/conf.d/api.nginx.conf
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=ana.loc
      - NGINX_PORT=80
    depends_on:
      - node
      - db
    logging:
      options:
        max-size: '12m'
        max-file: '5'
      driver: json-file
  api:
    build:
      context: ./
      dockerfile: dockerfiles/Dockerfile.api
    restart: always
    ports:
      - '3001:3001'
      - '3002:3002'
    container_name: api
    depends_on:
      - db
      - translate
    command: npm run start:server
    logging:
      options:
        max-size: '12m'
        max-file: '5'
      driver: json-file
  node:
    build:
      context: ./
      dockerfile: dockerfiles/Dockerfile.node
    restart: always
    ports:
      - '3000:3000'
    container_name: node
    depends_on:
      - api
    command: npm run start:app
    logging:
      options:
        max-size: '12m'
        max-file: '5'
      driver: json-file