version: '3.8'
services:
  db:
    container_name: pg
    image: postgres
    restart: always
    environment: # depends on .env
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    logging:
      options:
        max-size: '12m'
        max-file: '5'
      driver: json-file
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment: # depends on .env
      PGADMIN_DEFAULT_EMAIL: '${PGADMIN_EMAIL}'
      PGADMIN_DEFAULT_PASSWORD: '${PGADMIN_PASSWORD}'
    ports:
      - '5050:80'
    logging:
      options:
        max-size: '12m'
        max-file: '5'
      driver: json-file
  translate:
    build:
      container_name: translate
      context: ./
      dockerfile: ./dockerfiles/Dockerfile.translate
    restart: always
    ports:
      - '8000:8000'
    environment: # depends on .env
      CI: '${CI}'
    logging:
      options:
        max-size: '12m'
        max-file: '5'
      driver: json-file
