import Head from 'next/head';
import styles from '@/styles/Home.module.scss';
import Login from '@/components/Login';
import useTheme from '@/hooks/useTheme';

export default function HomePage() {
  const { theme } = useTheme();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>Home</main>
      <Login theme={theme} />
    </>
  );
}
