FROM python:3

WORKDIR /usr/src/app

COPY packages/translate2 .
RUN apt-get install sentencepiece
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt



CMD [ "python", "./main.py" ]