FROM node:18-alpine

WORKDIR /home/app

COPY package*.json ./

COPY packages/server ./packages/server
COPY packages/app/types/interfaces.ts ./packages/server/src/types/interfaces.ts

RUN npm --only-prod --ignore-scripts install
RUN npm run install:server

COPY .env.example ./.env
RUN npm run build:server