FROM nginx

RUN apt-get update
RUN apt-get install openssl -y
RUN mkdir /etc/nginx/certs

RUN openssl req -batch -newkey rsa:2048 -new -nodes -x509 -days 3650 -keyout /etc/nginx/certs/app.key.pem -out /etc/nginx/certs/app.cert.pem
RUN openssl req -batch -newkey rsa:2048 -new -nodes -x509 -days 3650 -keyout /etc/nginx/certs/ws.key.pem -out /etc/nginx/certs/ws.cert.pem
RUN openssl req -batch -newkey rsa:2048 -new -nodes -x509 -days 3650 -keyout /etc/nginx/certs/server.key.pem -out /etc/nginx/certs/server.cert.pem

COPY ./dockerfiles/resources/app.nginx.template /etc/nginx/conf.d/app.nginx.template
COPY ./dockerfiles/resources/ws.nginx.template /etc/nginx/conf.d/ws.nginx.template
COPY ./dockerfiles/resources/server.nginx.template /etc/nginx/conf.d/server.nginx.template

COPY scripts/sh/change-nginx-variables.sh /home