FROM nginx

RUN apt-get update
RUN apt-get install openssl -y
RUN mkdir /etc/nginx/certs

RUN openssl req -batch -newkey rsa:2048 -new -nodes -x509 -days 3650 -keyout /etc/nginx/certs/app.key.pem -out /etc/nginx/certs/app.cert.pem
RUN openssl req -batch -newkey rsa:2048 -new -nodes -x509 -days 3650 -keyout /etc/nginx/certs/ws.key.pem -out /etc/nginx/certs/ws.cert.pem
RUN openssl req -batch -newkey rsa:2048 -new -nodes -x509 -days 3650 -keyout /etc/nginx/certs/server.key.pem -out /etc/nginx/certs/server.cert.pem

COPY ./dockerfiles/resources/app.nginx.conf /etc/nginx/conf.d/app.nginx.conf
COPY ./dockerfiles/resources/ws.nginx.conf /etc/nginx/conf.d/ws.nginx.conf
COPY ./dockerfiles/resources/server.nginx.conf /etc/nginx/conf.d/server.nginx.conf
