FROM python:3

WORKDIR /usr/app

RUN apt-get update
# Install sentencepiece cli
RUN apt-get install -y curl zip unzip tar cmake
RUN git clone https://github.com/Microsoft/vcpkg.git
RUN cd vcpkg && ./bootstrap-vcpkg.sh && ./vcpkg integrate install && ./vcpkg install sentencepiece 
# Install dependencies
RUN pip install --upgrade pip
COPY packages/translate2/requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY packages/translate2 .

EXPOSE 8000
