name: Node CI

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened]
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v1
      - uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: dev
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Prepare environment
        run: |
          npm run scripts
          docker-compose -f docker-compose.ci.yml --env-file ./env up -d
      - name: Install dependencies
        run: |
          npm install --ignore-scripts
          npm run install:server
          npm run install:app
      - name: Build server
        run: |
          npm run build:server
      - name: Unit tests
        run: |
          npm run test
      - name: Test translate
        run: |
          npm run test:translate
